# Generated by Django 2.2.7 on 2019-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='nombreArchivo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
